repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: venv/bin/black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: venv/bin/isort
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: venv/bin/flake8
        language: system
        types: [python]
        exclude: ^(debug_links.py|verify_normalization_automated.py)
      - id: pydocstyle
        name: pydocstyle
        entry: venv/bin/pydocstyle
        args: [app]
        language: system
        types: [python]
        pass_filenames: false
